### ISSUE TITLE
Error when adding a bind function: Type 'string' is not assignable to type 'number'.

### ISSUE THREAD

**Issue by maietta** [fmaclen/svelte-currency-input#45]
Don't have time to contribute at the moment, but wondering if there is a workaround or way to easily implement a fix for binding values for use in watching form element changes like so:

I can normally use bind:value={formState.AskingPriceMax} in my forms, but not when using this component.

My TS error is: Type 'string' is not assignable to type 'number'.

```svelte
<label for="AskingPriceMax" class="font-medium text-green-900">Max:</label>
<div class="currency-input">
	<CurrencyInput
		name="AskingPriceMax"
		bind:value={formState.AskingPriceMax}
		isNegativeAllowed={false}
		fractionDigits={0}
		placeholder={999}
		locale="en-US"
		currency="USD"
	/>
</div>
```

**Comment by fmaclen** [comment]
@maietta _disregard my earlier message if you got a notification._

If you bind the value of any normal <input> tag the value is a `string`.
However, the value that this component is binding a `number` because it's already doing a type conversion.

The error you are seeing is because I imagine that `formState.AskingPriceMax` expects a `string`, here's an example of it working when AskingPriceMax is initialized as a number:
https://svelte.dev/repl/d8f7d22e5b384555b430f62b157ac503?version=3.50.1

**Comment by maietta** [comment]
I tried to respond earlier, but GitHub API is having issues (they are looking into it).

Thank you for the response on this. I'll be looking into this shortly.
